In [3]:
import numpy as np
import random

## Cоздание квадратной матрицы размерности n:

In [4]:
n=5
A = np.array([[random.random() for i in range(n)] for j in range(n)])*100
print(A)

[[17.5606118  47.44667774 50.67379203 87.60620498 62.78549645]
 [77.45771405 49.49204487 78.88836304 39.71153949 32.60762562]
 [84.69643356 23.37852436 26.14559196 19.12875046 59.47011278]
 [34.23967234 95.75780233 91.20589     7.82414091 37.88939954]
 [ 6.76870448 59.77684494 48.73341618 60.56356619 64.33022078]]


## Нахождение матриц L и U

In [5]:
L=np.eye(n)
U=A.copy()
P=np.eye(n)

cntP=1.
for i in range(n):
    maximum=0
    ind=i
    for j in range(i,n):
        if abs(U[j][i])>maximum:
            maximum=abs(U[j][i])
            ind=j
    if(i!=ind):
        U[[i,ind]]=U[[ind,i]]
        P[[i,ind]]=P[[ind,i]]
        cntP=-cntP
    
    U[i+1:,i] /= U[i,i]
    U[i+1:,i+1:] -= np.outer(U[i+1:,i], U[i,i+1:])
L=np.tril(U)
for i in range(n):
    L[i,i]=1.
U=np.triu(U)
print(f'L:\n{L}')
print(f'U:\n{U}')
print(f'P:\n{P}')
print(f'LU-PA:\n{L@U-P@A}')


    

L:
[[ 1.          0.          0.          0.          0.        ]
 [ 0.40426345  1.          0.          0.          0.        ]
 [ 0.91453336  0.32571745  1.          0.          0.        ]
 [ 0.20733591  0.49358231  0.1898906   1.          0.        ]
 [ 0.07991723  0.67096164 -0.25980989  0.81553113  1.        ]]
U:
[[ 84.69643356  23.37852436  26.14559196  19.12875046  59.47011278]
 [  0.          86.30671944  80.63618282   0.09108627  13.84780665]
 [  0.           0.          28.71273525  22.18799064 -26.29024874]
 [  0.           0.           0.          79.38187883  48.61244529]
 [  0.           0.           0.           0.           3.81075783]]
P:
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
LU-PA:
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00


## Вычисление определителя

In [6]:
print(np.linalg.det(A))
deter=cntP
for i in range(n):
    deter*=U[i][i]
    if abs(U[i][i])<1e-10:
        deter=0
        break
print(deter)

-63491709.92611861
-63491709.926119246


## Функции для решения системы с левой и правой треугольными матрицами:

In [7]:
def LSolution(A,b,n):
    y=np.zeros(n)
    for i in range(n):
        summ=0
        for j in range(i):
            summ+=A[i][j]*y[j]
        y[i]=(b[i]-summ)
    return y

def RSolution(A,b,n):
    x=np.zeros(n)
    for i in range(n-1,-1,-1):
        summ=0
        for j in range(i+1,n):
            summ+=A[i][j]*x[j]
        x[i]=(b[i]-summ)/A[i][i]
    return x

$$LUx=b$$
$$Ly=b$$
$$Ux=y$$
### Находим сначала y, а затем - х, используя предыдущие формулы
### Генерируем b размерности [nx1]


In [8]:
b=np.array([random.random() for i in range(n)])*100

print(b)
y = LSolution(L,P@b,n)
x=RSolution(U,y,n)
print(A@x-b)

[28.74963352 35.68718851 25.45919049 65.84635092  8.41696228]
[-7.10542736e-15  2.13162821e-13 -2.13162821e-14  1.13686838e-13
  1.68753900e-13]


### Функция, для нахождения решения(пригодится, чтобы найти обратную матрицу)

In [19]:
def findSol(P,U,L,b,n):
    return RSolution(U, LSolution(L,P@b,n),n)

### Находим обратную матрицу 

In [1]:
def InverseMatrix(P,U,L,n):
    E=np.eye(n)
    rev=np.empty((n,0))
    for i in range(n):
        x=findSol(P,U,L,E[:,i],n)
        rev=np.column_stack((rev,x))
    return rev

In [2]:
rev = (InverseMatrix(P,U,L,n))

print(f'A^(-1):\n{rev}')
print(f'A^(-1)*A:\n{rev@A}')
print(f'A*A^(-1):\n{A@rev}')

NameError: name 'P' is not defined

In [28]:
def MaxAbsElement(A,n):
    oness=np.ones(n)
    maxV = max(abs(A)@oness)
    return float(maxV)
            

## Нахождение числа обусловенности
### Метрика - $inf$

In [29]:
maximufOfA = MaxAbsElement(A,n)
maximumOfMinA = MaxAbsElement(rev,n)
condNumber = maximumOfMinA*maximufOfA
print(f'{maximumOfMinA}  *  {maximufOfA} = {condNumber}')

0.10409787635222892  *  270.54539787001016 = 28.163201375136897
